// Currency data with flags
  const currencyData = {
  USD: { code: "us", name: "US Dollar", flag: "🇺🇸" },
  EUR: { code: "eu", name: "Euro", flag: "🇪🇺" },
  GBP: { code: "gb", name: "British Pound", flag: "🇬🇧" },
  JPY: { code: "jp", name: "Japanese Yen", flag: "🇯🇵" },
  AUD: { code: "au", name: "Australian Dollar", flag: "🇦🇺" },
  CAD: { code: "ca", name: "Canadian Dollar", flag: "🇨🇦" },
  CHF: { code: "ch", name: "Swiss Franc", flag: "🇨🇭" },
  CNY: { code: "cn", name: "Chinese Yuan", flag: "🇨🇳" },
  INR: { code: "in", name: "Indian Rupee", flag: "🇮🇳" },
  SEK: { code: "se", name: "Swedish Krona", flag: "🇸🇪" },
  NZD: { code: "nz", name: "New Zealand Dollar", flag: "🇳🇿" },
  KRW: { code: "kr", name: "South Korean Won", flag: "🇰🇷" },
  SGD: { code: "sg", name: "Singapore Dollar", flag: "🇸🇬" },
  NOK: { code: "no", name: "Norwegian Krone", flag: "🇳🇴" },
  MXN: { code: "mx", name: "Mexican Peso", flag: "🇲🇽" },
  BRL: { code: "br", name: "Brazilian Real", flag: "🇧🇷" },
  ZAR: { code: "za", name: "South African Rand", flag: "🇿🇦" },
  HKD: { code: "hk", name: "Hong Kong Dollar", flag: "🇭🇰" },
  DKK: { code: "dk", name: "Danish Krone", flag: "🇩🇰" },
  PLN: { code: "pl", name: "Polish Zloty", flag: "🇵🇱" },
  THB: { code: "th", name: "Thai Baht", flag: "🇹🇭" },
  MYR: { code: "my", name: "Malaysian Ringgit", flag: "🇲🇾" },
  IDR: { code: "id", name: "Indonesian Rupiah", flag: "🇮🇩" },
  PHP: { code: "ph", name: "Philippine Peso", flag: "🇵🇭" },
  CZK: { code: "cz", name: "Czech Koruna", flag: "🇨🇿" },
  ILS: { code: "il", name: "Israeli Shekel", flag: "🇮🇱" },
  CLP: { code: "cl", name: "Chilean Peso", flag: "🇨🇱" },
  AED: { code: "ae", name: "UAE Dirham", flag: "🇦🇪" },
  COP: { code: "co", name: "Colombian Peso", flag: "🇨🇴" },
  SAR: { code: "sa", name: "Saudi Riyal", flag: "🇸🇦" },
  TRY: { code: "tr", name: "Turkish Lira", flag: "🇹🇷" },
  TWD: { code: "tw", name: "Taiwan Dollar", flag: "🇹🇼" },
  HUF: { code: "hu", name: "Hungarian Forint", flag: "🇭🇺" },
  RON: { code: "ro", name: "Romanian Leu", flag: "🇷🇴" },
  ARS: { code: "ar", name: "Argentine Peso", flag: "🇦🇷" },
  PKR: { code: "pk", name: "Pakistani Rupee", flag: "🇵🇰" },
  VND: { code: "vn", name: "Vietnamese Dong", flag: "🇻🇳" },
  EGP: { code: "eg", name: "Egyptian Pound", flag: "🇪🇬" },
  NGN: { code: "ng", name: "Nigerian Naira", flag: "🇳🇬" },
  BDT: { code: "bd", name: "Bangladeshi Taka", flag: "🇧🇩" },
  UAH: { code: "ua", name: "Ukrainian Hryvnia", flag: "🇺🇦" },
  PEN: { code: "pe", name: "Peruvian Sol", flag: "🇵🇪" },
  KES: { code: "ke", name: "Kenyan Shilling", flag: "🇰🇪" },

  // ———— Remaining currencies ————
  AFN: { code: "af", name: "Afghan Afghani", flag: "🇦🇫" },
  ALL: { code: "al", name: "Albanian Lek", flag: "🇦🇱" },
  AMD: { code: "am", name: "Armenian Dram", flag: "🇦🇲" },
  ANG: { code: "cw", name: "Netherlands Antillean Guilder", flag: "🇨🇼" },
  AOA: { code: "ao", name: "Angolan Kwanza", flag: "🇦🇴" },
  AWG: { code: "aw", name: "Aruban Florin", flag: "🇦🇼" },
  AZN: { code: "az", name: "Azerbaijani Manat", flag: "🇦🇿" },
  BAM: { code: "ba", name: "Bosnia Convertible Mark", flag: "🇧🇦" },
  BBD: { code: "bb", name: "Barbadian Dollar", flag: "🇧🇧" },
  BGN: { code: "bg", name: "Bulgarian Lev", flag: "🇧🇬" },
  BHD: { code: "bh", name: "Bahraini Dinar", flag: "🇧🇭" },
  BIF: { code: "bi", name: "Burundian Franc", flag: "🇧🇮" },
  BMD: { code: "bm", name: "Bermudian Dollar", flag: "🇧🇲" },
  BND: { code: "bn", name: "Brunei Dollar", flag: "🇧🇳" },
  BOB: { code: "bo", name: "Bolivian Boliviano", flag: "🇧🇴" },
  BSD: { code: "bs", name: "Bahamian Dollar", flag: "🇧🇸" },
  BTN: { code: "bt", name: "Bhutanese Ngultrum", flag: "🇧🇹" },
  BWP: { code: "bw", name: "Botswana Pula", flag: "🇧🇼" },
  BYN: { code: "by", name: "Belarusian Ruble", flag: "🇧🇾" },
  BZD: { code: "bz", name: "Belize Dollar", flag: "🇧🇿" },
  CDF: { code: "cd", name: "Congolese Franc", flag: "🇨🇩" },
  CRC: { code: "cr", name: "Costa Rican Colón", flag: "🇨🇷" },
  CUP: { code: "cu", name: "Cuban Peso", flag: "🇨🇺" },
  CVE: { code: "cv", name: "Cape Verdean Escudo", flag: "🇨🇻" },
  DJF: { code: "dj", name: "Djiboutian Franc", flag: "🇩🇯" },
  DOP: { code: "do", name: "Dominican Peso", flag: "🇩🇴" },
  DZD: { code: "dz", name: "Algerian Dinar", flag: "🇩🇿" },
  ERN: { code: "er", name: "Eritrean Nakfa", flag: "🇪🇷" },
  ETB: { code: "et", name: "Ethiopian Birr", flag: "🇪🇹" },
  FJD: { code: "fj", name: "Fijian Dollar", flag: "🇫🇯" },
  FKP: { code: "fk", name: "Falkland Islands Pound", flag: "🇫🇰" },
  GEL: { code: "ge", name: "Georgian Lari", flag: "🇬🇪" },
  GHS: { code: "gh", name: "Ghanaian Cedi", flag: "🇬🇭" },
  GIP: { code: "gi", name: "Gibraltar Pound", flag: "🇬🇮" },
  GMD: { code: "gm", name: "Gambian Dalasi", flag: "🇬🇲" },
  GNF: { code: "gn", name: "Guinean Franc", flag: "🇬🇳" },
  GTQ: { code: "gt", name: "Guatemalan Quetzal", flag: "🇬🇹" },
  GYD: { code: "gy", name: "Guyanese Dollar", flag: "🇬🇾" },
  HTG: { code: "ht", name: "Haitian Gourde", flag: "🇭🇹" },
  IQD: { code: "iq", name: "Iraqi Dinar", flag: "🇮🇶" },
  IRR: { code: "ir", name: "Iranian Rial", flag: "🇮🇷" },
  ISK: { code: "is", name: "Icelandic Krona", flag: "🇮🇸" },
  JMD: { code: "jm", name: "Jamaican Dollar", flag: "🇯🇲" },
  JOD: { code: "jo", name: "Jordanian Dinar", flag: "🇯🇴" },
  KGS: { code: "kg", name: "Kyrgyzstani Som", flag: "🇰🇬" },
  KHR: { code: "kh", name: "Cambodian Riel", flag: "🇰🇭" },
  KMF: { code: "km", name: "Comorian Franc", flag: "🇰🇲" },
  KWD: { code: "kw", name: "Kuwaiti Dinar", flag: "🇰🇼" },
  KYD: { code: "ky", name: "Cayman Islands Dollar", flag: "🇰🇾" },
  KZT: { code: "kz", name: "Kazakhstani Tenge", flag: "🇰🇿" },
  LAK: { code: "la", name: "Lao Kip", flag: "🇱🇦" },
  LBP: { code: "lb", name: "Lebanese Pound", flag: "🇱🇧" },
  LKR: { code: "lk", name: "Sri Lankan Rupee", flag: "🇱🇰" },
  LRD: { code: "lr", name: "Liberian Dollar", flag: "🇱🇷" },
  LSL: { code: "ls", name: "Lesotho Loti", flag: "🇱🇸" },
  LYD: { code: "ly", name: "Libyan Dinar", flag: "🇱🇾" },
  MAD: { code: "ma", name: "Moroccan Dirham", flag: "🇲🇦" },
  MDL: { code: "md", name: "Moldovan Leu", flag: "🇲🇩" },
  MGA: { code: "mg", name: "Malagasy Ariary", flag: "🇲🇬" },
  MKD: { code: "mk", name: "Macedonian Denar", flag: "🇲🇰" },
  MMK: { code: "mm", name: "Myanmar Kyat", flag: "🇲🇲" },
  MNT: { code: "mn", name: "Mongolian Tögrög", flag: "🇲🇳" },
  MOP: { code: "mo", name: "Macanese Pataca", flag: "🇲🇴" },
  MUR: { code: "mu", name: "Mauritian Rupee", flag: "🇲🇺" },
  MVR: { code: "mv", name: "Maldivian Rufiyaa", flag: "🇲🇻" },
  MWK: { code: "mw", name: "Malawian Kwacha", flag: "🇲🇼" },
  MZN: { code: "mz", name: "Mozambican Metical", flag: "🇲🇿" },
  NAD: { code: "na", name: "Namibian Dollar", flag: "🇳🇦" },
  NIO: { code: "ni", name: "Nicaraguan Córdoba", flag: "🇳🇮" },
  NPR: { code: "np", name: "Nepalese Rupee", flag: "🇳🇵" },
  OMR: { code: "om", name: "Omani Rial", flag: "🇴🇲" },
  PAB: { code: "pa", name: "Panamanian Balboa", flag: "🇵🇦" },
  PGK: { code: "pg", name: "Papua New Guinean Kina", flag: "🇵🇬" },
  PYD: { code: "py", name: "Paraguayan Guaraní", flag: "🇵🇾" },
  QAR: { code: "qa", name: "Qatari Riyal", flag: "🇶🇦" },
  RSD: { code: "rs", name: "Serbian Dinar", flag: "🇷🇸" },
  RUB: { code: "ru", name: "Russian Ruble", flag: "🇷🇺" },
  RWF: { code: "rw", name: "Rwandan Franc", flag: "🇷🇼" },
  SBD: { code: "sb", name: "Solomon Islands Dollar", flag: "🇸🇧" },
  SCR: { code: "sc", name: "Seychellois Rupee", flag: "🇸🇨" },
  SDG: { code: "sd", name: "Sudanese Pound", flag: "🇸🇩" },
  SHP: { code: "sh", name: "Saint Helena Pound", flag: "🇸🇭" },
  SLL: { code: "sl", name: "Sierra Leonean Leone", flag: "🇸🇱" },
  SOS: { code: "so", name: "Somali Shilling", flag: "🇸🇴" },
  SRD: { code: "sr", name: "Surinamese Dollar", flag: "🇸🇷" },
  SSP: { code: "ss", name: "South Sudanese Pound", flag: "🇸🇸" },
  STN: { code: "st", name: "São Tomé and Príncipe Dobra", flag: "🇸🇹" },
  SYP: { code: "sy", name: "Syrian Pound", flag: "🇸🇾" },
  SZL: { code: "sz", name: "Eswatini Lilangeni", flag: "🇸🇿" },
  TJS: { code: "tj", name: "Tajikistani Somoni", flag: "🇹🇯" },
  TMT: { code: "tm", name: "Turkmenistani Manat", flag: "🇹🇲" },
  TND: { code: "tn", name: "Tunisian Dinar", flag: "🇹🇳" },
  TOP: { code: "to", name: "Tongan Paʻanga", flag: "🇹🇴" },
  TTD: { code: "tt", name: "Trinidad and Tobago Dollar", flag: "🇹🇹" },
  UGX: { code: "ug", name: "Ugandan Shilling", flag: "🇺🇬" },
  UYU: { code: "uy", name: "Uruguayan Peso", flag: "🇺🇾" },
  UZS: { code: "uz", name: "Uzbekistani Som", flag: "🇺🇿" },
  VES: { code: "ve", name: "Venezuelan Bolívar", flag: "🇻🇪" },
  WST: { code: "ws", name: "Samoan Tālā", flag: "🇼🇸" },
  XAF: { code: "cm", name: "Central African CFA Franc", flag: "🇨🇲" },
  XCD: { code: "ag", name: "East Caribbean Dollar", flag: "🇦🇬" },
  XOF: { code: "sn", name: "West African CFA Franc", flag: "🇸🇳" },
  XPF: { code: "pf", name: "CFP Franc", flag: "🇵🇫" },
  YER: { code: "ye", name: "Yemeni Rial", flag: "🇾🇪" },
  ZMW: { code: "zm", name: "Zambian Kwacha", flag: "🇿🇲" },
  ZWL: { code: "zw", name: "Zimbabwe Dollar", flag: "🇿🇼" }
};

const popularCurrencies = [
  "USD",
  "EUR",
  "GBP",
  "JPY",
  "AUD",
  "CAD",
  "CHF",
  "CNY",
  "INR",
  "MXN",
];
